services:
  recommender:
    build:
      context: .
      dockerfile: recommend/Dockerfile.recommender
    container_name: recommender_server
    volumes:
      - repo_recommender_data:/usr/src/data
    networks:
      - app_network
    environment:
      PORT: ${RECOMMENDATION_PORT:-5555} 
    entrypoint: ["./myapp"]
    command: [$RECOMMENDATION_PORT]

  app:
    build:
      context: .
      dockerfile: api/Dockerfile.server
    container_name: app_server
    ports:
      - "${APP_PORT:-3000}:${CONTAINER_PORT:-3000}"
    volumes:
      - uploads_data:/usr/src/app/uploads
    networks:
      - app_network
    environment:
      CONNECTION_STRING: ${CONNECTION_STRING}
      RECOMMENDATION_IP: recommender_server  
      RECOMMENDATION_PORT: ${RECOMMENDATION_PORT:-5555}
      PORT: ${CONTAINER_PORT:-3000} 
      JWT_SECRET: ${JWT_SECRET}

    command: ["npm", "start"]
  react:
    build:
      context: ./netflix
      dockerfile: Dockerfile.react
    container_name: react_app
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - app_network
    command: ["npm", "start"]  


volumes:
  repo_recommender_data:
  uploads_data:

networks:
  app_network:
    driver: bridge